# Generated by Django 5.1.2 on 2024-12-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
