# Generated by Django 5.1.2 on 2024-12-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
